### ISSUE TITLE
Failed send file if there are spaces in name or path

### ISSUE THREAD

**Issue by nandakista** [cometchat-pro/cometchat-chat-sample-app-flutter#16]
### Describe the problem

Failed to send file when there are spaces in the path.
I am sorry, I know this issue is in cometchat_chat_uikit, but I have search the repository of cometchat_chat_uikit but I cant found it. So I reported this issue here.

### What was the expected behavior?

File successfully send or give the documentation how to resolve this issue.

### Reproduction

- Step 1 : Run the app 
- Step 2 : send files that have spaces in the path

Exception : Invalid message object received

SS : 
<img width="1135" alt="Screenshot 2023-09-22 at 10 41 12" src="https://github.com/cometchat-pro/cometchat-chat-sample-app-flutter/assets/47182823/1ffbd9e7-ba7a-4691-9e80-5f9dd543cdd0">

### Environment

cometchat_chat_uikit: ^4.0.0
flutter version 3.10.6

**Comment by Kamran73** [comment]
you can use this
removeUriSpaces(String string) {
    return string.replaceAll(' ', '');
  }
  
  or if you want to use extension method then
  extension UriExtension on String {
  String removeUriSpaces() {
    return this.replaceAll(' ', '');
  }
}

**Comment by nandakista** [comment]
> you can use this removeUriSpaces(String string) { return string.replaceAll(' ', ''); }
> 
> or if you want to use extension method then extension UriExtension on String { String removeUriSpaces() { return this.replaceAll(' ', ''); } }

Thank you for the response, 
But the function of send file is in ui kit or handled by ui kit, and cannot using onSendButtonTap property in messageComposerConfiguration because the file will automatically sending without tap button send.

So should I wait for updates from cometchat_chat_uikit ?
I tried posting the issue but didn't find the repository on Github, nor did pub.dev list their repository

**Comment by proveshapyne** [comment]
Hello @nandakista,

Thank you for the additional details. We have taken this report and sent the notified our product engineering team who will be investigating. 
We will reach out when we have more information on this.

Provesha Pyne
CometChat

**Comment by nandakista** [comment]
Hello @proveshapyne 
Any update for this issue ?

**Comment by proveshapyne** [comment]
Hey @nandakista,

Thank you for enquiring! 
Our team has taken up this task but I cannot provide you with a specific timeline at this moment. Nevertheless, I assure you that we will update you as soon as we have more information.

In the meantime, please feel free to [submit a new request](https://help.cometchat.com/hc/en-us/requests/new) if you need a hand with anything else.

**Comment by nandakista** [comment]
Hi,
I upgrade to cometchat_chat_uikit: ^4.0.4 and I see in the cometchat_uikit_shared: ^4.0.4 changelog, it solved the issue
I've tested and it really solved the issue.
Thank you for the update and response

Close the issue for now
